Ft signup validation #184638231
atlp-rwanda/rca-barefoot-team4-bn pull request #25
Opened 2023-03-23 13:30 UTC by nshimiyeemmy

What does this PR do?

This PR adds request validation to the request body before registering a user. It validates that all required fields are set and are in acceptable format and within a specified character range.

Description of Task to be completed?

Create a user schema for an acceptable data format to register a new user
Validated request body against the Shema in auth.controller
Return detailed error message when validation fails

How should this be manually tested?

Start your local development server
Open postman and send a POST request to localhost:3000/api/v1/auth/register
set request body type to JSON
use a request body that does not include all required fields or a password of 3 characters or a malformed email

Relevant Pivotal Tracker task

Users should receive descriptive signup/Registration validation errors

Task with ID: #184638231

2023-03-23 13:38 UTC, nshimiyeemmy commented on src/types/token.ts
> +export interface Tokens {
DONE. allowed ECMA script modules in eslint config

2023-03-24 12:25 UTC, iradukundairenee requested changes
please fix the error in the github actions.

2023-03-29 13:39 UTC, gershomlapaix reviewed
ready

2023-03-29 13:54 UTC, iradukundairenee commented
> ready

@gershomlapaix  do you mean this PR is for being approved?

2023-03-29 14:14 UTC, iradukundairenee approved these changes

2023-03-29 14:21 UTC, gershomlapaix approved these changes

2023-03-29 14:26 UTC, merged