refactor: moved the @types/ dependencies to devDependencies
atlp-rwanda/rca-barefoot-team4-bn pull request #4
Opened 2023-03-09 09:02 UTC by MerlyneIradukunda

- removed the @types/ from dependencies to devDependencies

[Delivers #184638222]

2023-03-09 11:31 UTC, Anguandia commented
@iradukundairenee please assign reviewers for this PR

2023-03-09 15:01 UTC, iradukundairenee requested changes
@MerlyneIradukunda  add descriptipon on this PR

2023-03-10 13:51 UTC, aimee-annabelle approved these changes

2023-03-10 14:11 UTC, ishgervais approved these changes

2023-03-10 14:11 UTC, iradukundairenee approved these changes

2023-03-10 14:51 UTC, merged