Ch setup dotenv 184638224
atlp-rwanda/rca-barefoot-team4-bn pull request #5
Opened 2023-03-09 12:09 UTC by AngeNicole

<b>What does this PR do?</b>

- loads environment variables
- store configurations

<b>Description of Task to be completed</b>

- This is a file that helps in accessing your application's environment variables

<b>How should this be manually tested?</b>

- Cloning this repository to your local machine.
- Switch to a branch named ch-setup-dotenv-184638224
- Open Terminal on your code editor and type yarn
- Create a file in root called .env and insert
![image](https://user-images.githubusercontent.com/55019052/224017918-c318e17d-0429-454b-b148-3431eee16b6e.png)

2023-03-09 12:41 UTC, iradukundairenee commented
@AngeNicole  request at least 3 reviewrs including me ,manager and sprint lead

2023-03-09 12:49 UTC, iradukundairenee requested changes
you are not allowed to push .env file

2023-03-09 12:49 UTC, iradukundairenee commented on package.json
>    },
have you make rebase ?

2023-03-09 14:57 UTC, iradukundairenee commented
remember to squash your commit 3 commit is not Good practice

2023-03-10 10:45 UTC, ishgervais approved these changes

2023-03-10 22:31 UTC, closed without merging